# -*- coding: utf-8 -*-
"""CareerPilot_AI_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3LRgSVWr1Ay0ISD-h1Pw0xJwlBUII8f
"""

!pip install -q langgraph langchain langchain-groq

"""#Import Libraries"""

import pandas as pd
import textwrap

"""#Upload CSV Files"""

from google.colab import files

uploaded = files.upload()

from backend.app.config import career_df, llm, projects_df

print("Career Domains")
display(career_df.head())

print("\nProjects")
display(projects_df.head())

"""#Create Shared Memory"""

from backend.app.state import CareerState
from backend.app.prompts import (
    FINAL_REPORT_FOOTER,
    FINAL_REPORT_PROJECT_LINE,
    FINAL_REPORT_TEMPLATE,
    ROLE_MATCH_SYSTEM_PROMPT,
    ROLE_MATCH_USER_PROMPT_TEMPLATE,
    ROLE_NOT_FOUND_TEMPLATE,
    ROADMAP_SYSTEM_PROMPT,
    ROADMAP_USER_PROMPT_TEMPLATE,
    SKILL_ANALYSIS_SYSTEM_PROMPT,
    SKILL_ANALYSIS_USER_PROMPT_TEMPLATE,
)

"""#Student Intake Node"""

def intake_node(state: CareerState) -> CareerState:
    print("========== CareerPilot AI ==========\n")

    name = input("Enter your name: ")
    education = input("Enter your education: ")
    target_role = input("Enter your dream job role: ")

    print("\nEnter your current skills (comma separated)")
    print("Example: Java, HTML, CSS, SQL\n")

    skills = input("Skills: ")

    current_skills = [
        skill.strip()
        for skill in skills.split(",")
        if skill.strip()
    ]

    return {
        "name": name,
        "education": education,
        "target_role": target_role,
        "current_skills": current_skills,

        "required_skills": [],
        "missing_skills": [],
        "reasoning": "",

        "roadmap": "",
        "recommended_projects": [],

        "final_report": ""
    }

"""#Role Matching Agent"""

def role_matching_node(state: CareerState) -> CareerState:

    # Get all available roles from the CSV
    available_roles = career_df["role"].tolist()

    prompt = ROLE_MATCH_USER_PROMPT_TEMPLATE.format(
        target_role=state["target_role"],
        available_roles="\n".join(available_roles),
    )

    response = llm.invoke(
        [
            SystemMessage(content=ROLE_MATCH_SYSTEM_PROMPT),
            HumanMessage(content=prompt)
        ]
    )

    matched_role = response.content.strip()

    print(f"Matched Role: {matched_role}")

    return {
        **state,
        "target_role": matched_role
    }

"""#Skill Analysis Node"""

from langchain_core.messages import SystemMessage, HumanMessage

def skill_analysis_node(state: CareerState) -> CareerState:

    target_role = state["target_role"]

    # Search for the selected role
    role_data = career_df[
        career_df["role"].str.lower() == target_role.lower()
    ]

    # Role not found
    if role_data.empty:
        return {
            **state,
            "reasoning": ROLE_NOT_FOUND_TEMPLATE.format(target_role=target_role)
        }

    # Extract required skills from CSV
    required_skills = [
        skill.strip()
        for skill in role_data.iloc[0]["required_skills"].split(";")
    ]

    # Convert current skills to lowercase for comparison
    current_skills_lower = {
        skill.lower()
        for skill in state["current_skills"]
    }

    # Find missing skills
    missing_skills = [
        skill
        for skill in required_skills
        if skill.lower() not in current_skills_lower
    ]

    # Prompt for LLM
    prompt = SKILL_ANALYSIS_USER_PROMPT_TEMPLATE.format(
        education=state["education"],
        target_role=target_role,
        current_skills=", ".join(state["current_skills"]),
        required_skills=", ".join(required_skills),
        missing_skills=", ".join(missing_skills),
    )

    response = llm.invoke(
        [
            SystemMessage(content=SKILL_ANALYSIS_SYSTEM_PROMPT),
            HumanMessage(content=prompt)
        ]
    )

    return {
        **state,
        "required_skills": required_skills,
        "missing_skills": missing_skills,
        "reasoning": response.content
    }

"""#Roadmap Generation Node"""

def roadmap_node(state: CareerState) -> CareerState:

    prompt = ROADMAP_USER_PROMPT_TEMPLATE.format(
        name=state["name"],
        education=state["education"],
        target_role=state["target_role"],
        current_skills=", ".join(state["current_skills"]),
        missing_skills=", ".join(state["missing_skills"]),
    )

    response = llm.invoke(
        [
            SystemMessage(content=ROADMAP_SYSTEM_PROMPT),
            HumanMessage(content=prompt)
        ]
    )

    return {
        **state,
        "roadmap": response.content
    }

"""#Project Recommendation Node"""

def project_recommendation_node(state: CareerState) -> CareerState:

    role = state["target_role"].lower()

    filtered_projects = projects_df[
        projects_df["target_roles"].str.lower().str.contains(role, na=False)
    ]

    recommended_projects = filtered_projects["project_name"].tolist()

    return {
        **state,
        "recommended_projects": recommended_projects
    }

"""#Final Report Node"""

def final_report_node(state: CareerState) -> CareerState:

    report = FINAL_REPORT_TEMPLATE.format(
        name=state["name"],
        education=state["education"],
        target_role=state["target_role"],
        current_skills=", ".join(state["current_skills"]),
        required_skills=", ".join(state["required_skills"]),
        missing_skills=", ".join(state["missing_skills"]),
        reasoning=state["reasoning"],
        roadmap=state["roadmap"],
    )

    for project in state["recommended_projects"]:
        report += FINAL_REPORT_PROJECT_LINE.format(project=project)

    report += FINAL_REPORT_FOOTER

    print(report)

    return {
        **state,
        "final_report": report
    }

"""#Build the Graph"""

from langgraph.graph import StateGraph, END

builder = StateGraph(CareerState)

# Nodes
builder.add_node("intake", intake_node)
builder.add_node("role_match", role_matching_node)      # NEW
builder.add_node("skill_analysis", skill_analysis_node)
builder.add_node("roadmap", roadmap_node)
builder.add_node("projects", project_recommendation_node)
builder.add_node("report", final_report_node)

# Entry Point
builder.set_entry_point("intake")

# Flow
builder.add_edge("intake", "role_match")
builder.add_edge("role_match", "skill_analysis")
builder.add_edge("skill_analysis", "roadmap")
builder.add_edge("roadmap", "projects")
builder.add_edge("projects", "report")
builder.add_edge("report", END)

graph = builder.compile()

"""#Print Graph"""

from IPython.display import Image, display

display(Image(graph.get_graph().draw_mermaid_png()))

"""#Run the Agent"""

final_state = graph.invoke({})